databases:
  - name: todo-db
    databaseName: todo
    user: todo_user
    plan: free

services:
  - type: web
    name: django-todo-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn TODO.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: "False"
